apiVersion: v1
kind: Service
metadata:
  name: {{ template "resolver-exporter.fullname" . }}
  annotations:
      prometheus.io/scrape: "true"
      prometheus.io/path: "/metrics"
      prometheus.io/port: "8080"
  labels:
    app: {{ template "resolver-exporter.name" . }}
    chart: {{ template "resolver-exporter.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ template "resolver-exporter.name" . }}
    release: {{ .Release.Name }}
